name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy with SSH
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSHKEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/greenaral.uz
            git pull
            yarn install
            yarn build
            pm2 restart greenaral.uz